USE `db_second_hub`;

-- 为user表添加个人信息字段
ALTER TABLE `user` ADD COLUMN `bio` VARCHAR(500) DEFAULT NULL;
ALTER TABLE `user` ADD COLUMN `gender` TINYINT DEFAULT NULL COMMENT '1男 2女 0未知';
ALTER TABLE `user` ADD COLUMN `birthday` DATE DEFAULT NULL;
ALTER TABLE `user` ADD COLUMN `interests` VARCHAR(500) DEFAULT NULL;
ALTER TABLE `user` ADD COLUMN `school` VARCHAR(128) DEFAULT NULL;